spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: qwer1234
#    url: jdbc:mysql://localhost:3306/project

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true

jwt:
  secret: ${JWT}
  token.expired-time-ms: 2592000000 # 30 days